### ISSUE TITLE
Create a tutorials website

### ISSUE THREAD

**Issue by bhajneet** [ShabadOS/tutorials#1]
A website to basically have a table of contents of all the different tutorials we have (based on folder name) and then a pretty markup view of the tutorial.

To be linked from within Shabad OS or used standalone as links sent to users asking for help.

**Comment by Harjot1Singh** [comment]
Would this suffice? https://docs.antora.org/antora/2.2/features/

**Comment by bhajneet** [comment]
If you can explain the file structure to get that, it should be fine for
now. Can always improve later as we expand if needed.

**Comment by Harjot1Singh** [comment]
done
