### ISSUE TITLE
EOL: Archive this repo and redirect to docs

### ISSUE THREAD

**Issue by saihaj** [shabados/tutorials#10]
As mentioned by @bhajneet in https://github.com/shabados/docs/pull/67 all content from this repo has been migrated to [`shabados/docs`](https://github.com/shabados/docs)
> Can probably delete the tutorials repo and point it to docs.shabados.com now.

We should probably archive this repo and mentioned in that PR redirect `tutorials.shabados.com` -> `docs.shabados.com`
ping @Harjot1Singh

**Comment by Harjot1Singh** [comment]
Done
