### ISSUE TITLE
Convert to docs repo and have antora pull from mulitple repos

### ISSUE THREAD

**Issue by bhajneet** [shabados/tutorials#8]
Our docs are leveraging multiple styles from docsify, handlebars, and now ascii doc. It would be nice if all our technical documentation / practical tutorials were in a similar format/style via antora.

Can database docs and gurmukhi-utils docs be formatted in antora properly and convert this repo to "docs" replace previous docs.shabados.com url?

**Comment by bhajneet** [comment]
https://antora.org/

**Comment by saihaj** [comment]
Docsify is good but https://docusaurus.io/en/ (react app) this provides easy versioning and we also get search  functionality (similar to docsify), supports localization we just need to work on the UI for this  and can be easily deployed to gh-pages

**Comment by bhajneet** [comment]
What's the benefit of docusaurus over antora and I'm not keen to get going on v1 only to have v2 ready a short while later

**Comment by saihaj** [comment]
resolved by creating and migrating to https://github.com/shabados/docs
